### ISSUE TITLE
Revert changes?

### ISSUE THREAD

**Issue by ppranav06** [dominichayesferen/kde-plasma-hellcreator#1]
Hi, 

Read through the script, it is indeed a good one. Is there a way to **revert the changes** made by the script? 

In future versions, please backup the existing configuration too :)

Thank you

**Comment by dominichayesferen** [comment]
It's just a colour scheme. You... just apply your prior colour scheme again, and profit.

_Same with your accent colour, if you use withaccent.py instead._
